import { NextUIProvider } from "@nextui-org/react";
import "./globals.css";
import Header from "@/components/layout/header";

export const metadata = {
  title: "Travellian",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <NextUIProvider className="default relative">
          <Header />
          <main className="h-auto w-full relative">
            {children}
          </main>
        </NextUIProvider>
      </body>
    </html>
  );
}
